markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
title: Jack's Blog sssssssssss
description: Jack's Blog, powered by Jekyll...
feed: http://www.winfirm.cn/atom.xml

author: Jack

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
